In [1]:
import pandas as pd
import numpy as np
import glob, os
import re

# 

In [6]:
ls sports_data_raw/MLS

HOU/  mls.csv*


In [7]:
path = 'sports_data_raw/MLS/mls.csv'
df = pd.read_csv(path)

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 16 columns):
Date        4995 non-null object
Season      4995 non-null int64
home        4995 non-null object
visitor     4995 non-null object
FT          4995 non-null object
hgoal       4995 non-null int64
vgoal       4995 non-null int64
hconf       4995 non-null object
vconf       4995 non-null object
totgoal     4995 non-null int64
round       4995 non-null object
leg         237 non-null float64
hgoalaet    47 non-null float64
vgoalaet    47 non-null float64
hpen        23 non-null float64
vpen        23 non-null float64
dtypes: float64(5), int64(4), object(7)
memory usage: 624.5+ KB


In [9]:
df.head()

Date  Season                  home                 visitor   FT  \
0  1996-04-06    1996  San Jose Earthquakes               DC United  1-0   
1  1996-04-13    1996             LA Galaxy      New York Red Bulls  2-1   
2  1996-04-13    1996      Tampa Bay Mutiny  New England Revolution  3-2   
3  1996-04-13    1996         Columbus Crew               DC United  4-0   
4  1996-04-13    1996  Sporting Kansas City         Colorado Rapids  3-0   

   hgoal  vgoal hconf vconf  totgoal    round  leg  hgoalaet  vgoalaet  hpen  \
0      1      0  West  East        1  regular  NaN       NaN       NaN   NaN   
1      2      1  West  East        3  regular  NaN       NaN       NaN   NaN   
2      3      2  East  East        5  regular  NaN       NaN       NaN   NaN   
3      4      0  East  East        4  regular  NaN       NaN       NaN   NaN   
4      3      0  West  West        3  regular  NaN       NaN       NaN   NaN   

   vpen  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

## Create slice with only needed columns

In [10]:
mls = df[['Date','Season','home','hgoal' , 'visitor','vgoal']]

In [11]:
mls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 6 columns):
Date       4995 non-null object
Season     4995 non-null int64
home       4995 non-null object
hgoal      4995 non-null int64
visitor    4995 non-null object
vgoal      4995 non-null int64
dtypes: int64(3), object(3)
memory usage: 234.2+ KB


In [12]:
mls.head()

Date  Season                  home  hgoal                 visitor  \
0  1996-04-06    1996  San Jose Earthquakes      1               DC United   
1  1996-04-13    1996             LA Galaxy      2      New York Red Bulls   
2  1996-04-13    1996      Tampa Bay Mutiny      3  New England Revolution   
3  1996-04-13    1996         Columbus Crew      4               DC United   
4  1996-04-13    1996  Sporting Kansas City      3         Colorado Rapids   

   vgoal  
0      0  
1      1  
2      2  
3      0  
4      0

## Inspect Data

In [13]:
mls.Date.unique()

array(['1996-04-06', '1996-04-13', '1996-04-14', ..., '2016-11-27',
       '2016-11-30', '2016-12-10'], dtype=object)

In [14]:
mls.Season.unique()

array([1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [15]:
mls.home.unique()

array(['San Jose Earthquakes', 'LA Galaxy', 'Tampa Bay Mutiny',
       'Columbus Crew', 'Sporting Kansas City', 'FC Dallas', 'DC United',
       'New York Red Bulls', 'Colorado Rapids', 'New England Revolution',
       'Miami Fusion', 'Chicago Fire', 'CD Chivas USA', 'Real Salt Lake',
       'Houston Dynamo', 'Toronto FC', 'Seattle Sounders',
       'Philadelphia Union', 'Vancouver Whitecaps', 'Portland Timbers',
       'Montreal Impact', 'Orlando City', 'New York City FC'],
      dtype=object)

In [16]:
mls.home.value_counts(dropna=False)

LA Galaxy                 370
DC United                 358
FC Dallas                 353
New York Red Bulls        353
Sporting Kansas City      352
New England Revolution    352
Colorado Rapids           351
Columbus Crew             350
Chicago Fire              324
San Jose Earthquakes      309
Real Salt Lake            203
Houston Dynamo            191
Toronto FC                166
CD Chivas USA             164
Seattle Sounders          146
Philadelphia Union        118
Portland Timbers          107
Vancouver Whitecaps       103
Tampa Bay Mutiny          100
Montreal Impact            89
Miami Fusion               67
New York City FC           35
Orlando City               34
Name: home, dtype: int64

In [17]:
mls.hgoal.unique()

array([1, 2, 3, 4, 0, 6, 5, 7])

In [18]:
mls.visitor.unique()

array(['DC United', 'New York Red Bulls', 'New England Revolution',
       'Colorado Rapids', 'San Jose Earthquakes', 'Sporting Kansas City',
       'LA Galaxy', 'Tampa Bay Mutiny', 'FC Dallas', 'Columbus Crew',
       'Chicago Fire', 'Miami Fusion', 'Real Salt Lake', 'CD Chivas USA',
       'Houston Dynamo', 'Toronto FC', 'Seattle Sounders',
       'Philadelphia Union', 'Portland Timbers', 'Vancouver Whitecaps',
       'Montreal Impact', 'New York City FC', 'Orlando City'],
      dtype=object)

In [19]:
mls.visitor.value_counts(dropna=False)

LA Galaxy                 365
Sporting Kansas City      356
New York Red Bulls        356
Columbus Crew             354
New England Revolution    353
FC Dallas                 352
Colorado Rapids           351
DC United                 350
Chicago Fire              318
San Jose Earthquakes      314
Real Salt Lake            208
Houston Dynamo            193
Toronto FC                165
CD Chivas USA             164
Seattle Sounders          144
Philadelphia Union        119
Portland Timbers          107
Vancouver Whitecaps       104
Tampa Bay Mutiny           98
Montreal Impact            90
Miami Fusion               65
New York City FC           35
Orlando City               34
Name: visitor, dtype: int64

In [20]:
mls.vgoal.unique()

array([0, 1, 2, 3, 4, 5, 8, 6, 7])

## Date column



In [21]:
mls['Date'] = pd.to_datetime(mls['Date'])

mls = mls.set_index('Date').sort_index(ascending=True)

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [22]:
#mls.loc['2008':'2015']

In [23]:
mls.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4995 entries, 1996-04-06 to 2016-12-10
Data columns (total 5 columns):
Season     4995 non-null int64
home       4995 non-null object
hgoal      4995 non-null int64
visitor    4995 non-null object
vgoal      4995 non-null int64
dtypes: int64(3), object(2)
memory usage: 234.1+ KB


## Winner column
- create new colum with the winner value

In [24]:
mls['winner'] = np.where(mls['hgoal'] > mls['vgoal'], mls['home'], mls['visitor'])

In [25]:
mls.head()

Season                  home  hgoal                 visitor  \
Date                                                                      
1996-04-06    1996  San Jose Earthquakes      1               DC United   
1996-04-13    1996             LA Galaxy      2      New York Red Bulls   
1996-04-13    1996      Tampa Bay Mutiny      3  New England Revolution   
1996-04-13    1996         Columbus Crew      4               DC United   
1996-04-13    1996  Sporting Kansas City      3         Colorado Rapids   

            vgoal                winner  
Date                                     
1996-04-06      0  San Jose Earthquakes  
1996-04-13      1             LA Galaxy  
1996-04-13      2      Tampa Bay Mutiny  
1996-04-13      0         Columbus Crew  
1996-04-13      0  Sporting Kansas City

In [ ]:
mls.info()

## Save clean version to csv

In [ ]:
mls.to_csv('clean_data/mls_clean.csv')

## Select from 2008: 2016

In [ ]:
mls_08_16 = mls.loc['2008':'2016']

In [ ]:
mls_08_16.info()

## Save clean version to csv

In [ ]:
mls_08_16.to_csv('clean_data/mls_08_16_clean.csv')

In [ ]:
ls clean_data/

In [ ]:
## Finish

In [ ]:
mls_08_16