In [1]:
import pandas as pd
import numpy as np
import glob, os
import re

# 

In [66]:
ls sports_data/MLS/

HOU/  mls.csv*


In [3]:
path = 'sports_data/MLS/mls.csv'
df = pd.read_csv(path)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 16 columns):
Date        4995 non-null object
Season      4995 non-null int64
home        4995 non-null object
visitor     4995 non-null object
FT          4995 non-null object
hgoal       4995 non-null int64
vgoal       4995 non-null int64
hconf       4995 non-null object
vconf       4995 non-null object
totgoal     4995 non-null int64
round       4995 non-null object
leg         237 non-null float64
hgoalaet    47 non-null float64
vgoalaet    47 non-null float64
hpen        23 non-null float64
vpen        23 non-null float64
dtypes: float64(5), int64(4), object(7)
memory usage: 624.5+ KB


In [6]:
df.head()

Date  Season                  home                 visitor   FT  \
0  1996-04-06    1996  San Jose Earthquakes               DC United  1-0   
1  1996-04-13    1996             LA Galaxy      New York Red Bulls  2-1   
2  1996-04-13    1996      Tampa Bay Mutiny  New England Revolution  3-2   
3  1996-04-13    1996         Columbus Crew               DC United  4-0   
4  1996-04-13    1996  Sporting Kansas City         Colorado Rapids  3-0   

   hgoal  vgoal hconf vconf  totgoal    round  leg  hgoalaet  vgoalaet  hpen  \
0      1      0  West  East        1  regular  NaN       NaN       NaN   NaN   
1      2      1  West  East        3  regular  NaN       NaN       NaN   NaN   
2      3      2  East  East        5  regular  NaN       NaN       NaN   NaN   
3      4      0  East  East        4  regular  NaN       NaN       NaN   NaN   
4      3      0  West  West        3  regular  NaN       NaN       NaN   NaN   

   vpen  
0   NaN  
1   NaN  
2   NaN  
3   NaN  
4   NaN

## Create slice with only needed columns

In [18]:
mls = df[['Date','Season','home','hgoal' , 'visitor','vgoal']]

In [19]:
mls.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4995 entries, 0 to 4994
Data columns (total 6 columns):
Date       4995 non-null object
Season     4995 non-null int64
home       4995 non-null object
hgoal      4995 non-null int64
visitor    4995 non-null object
vgoal      4995 non-null int64
dtypes: int64(3), object(3)
memory usage: 234.2+ KB


In [20]:
mls.head()

Date  Season                  home  hgoal                 visitor  \
0  1996-04-06    1996  San Jose Earthquakes      1               DC United   
1  1996-04-13    1996             LA Galaxy      2      New York Red Bulls   
2  1996-04-13    1996      Tampa Bay Mutiny      3  New England Revolution   
3  1996-04-13    1996         Columbus Crew      4               DC United   
4  1996-04-13    1996  Sporting Kansas City      3         Colorado Rapids   

   vgoal  
0      0  
1      1  
2      2  
3      0  
4      0

## Inspect Data

In [21]:
mls.Date.unique()

array(['1996-04-06', '1996-04-13', '1996-04-14', ..., '2016-11-27',
       '2016-11-30', '2016-12-10'], dtype=object)

In [22]:
mls.Season.unique()

array([1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006,
       2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016])

In [25]:
mls.home.unique()

array(['San Jose Earthquakes', 'LA Galaxy', 'Tampa Bay Mutiny',
       'Columbus Crew', 'Sporting Kansas City', 'FC Dallas', 'DC United',
       'New York Red Bulls', 'Colorado Rapids', 'New England Revolution',
       'Miami Fusion', 'Chicago Fire', 'CD Chivas USA', 'Real Salt Lake',
       'Houston Dynamo', 'Toronto FC', 'Seattle Sounders',
       'Philadelphia Union', 'Vancouver Whitecaps', 'Portland Timbers',
       'Montreal Impact', 'Orlando City', 'New York City FC'],
      dtype=object)

In [27]:
mls.home.value_counts(dropna=False)

LA Galaxy                 370
DC United                 358
New York Red Bulls        353
FC Dallas                 353
New England Revolution    352
Sporting Kansas City      352
Colorado Rapids           351
Columbus Crew             350
Chicago Fire              324
San Jose Earthquakes      309
Real Salt Lake            203
Houston Dynamo            191
Toronto FC                166
CD Chivas USA             164
Seattle Sounders          146
Philadelphia Union        118
Portland Timbers          107
Vancouver Whitecaps       103
Tampa Bay Mutiny          100
Montreal Impact            89
Miami Fusion               67
New York City FC           35
Orlando City               34
Name: home, dtype: int64

In [32]:
mls.hgoal.unique()

array([1, 2, 3, 4, 0, 6, 5, 7])

In [29]:
mls.visitor.unique()

array(['DC United', 'New York Red Bulls', 'New England Revolution',
       'Colorado Rapids', 'San Jose Earthquakes', 'Sporting Kansas City',
       'LA Galaxy', 'Tampa Bay Mutiny', 'FC Dallas', 'Columbus Crew',
       'Chicago Fire', 'Miami Fusion', 'Real Salt Lake', 'CD Chivas USA',
       'Houston Dynamo', 'Toronto FC', 'Seattle Sounders',
       'Philadelphia Union', 'Portland Timbers', 'Vancouver Whitecaps',
       'Montreal Impact', 'New York City FC', 'Orlando City'],
      dtype=object)

In [30]:
mls.visitor.value_counts(dropna=False)

LA Galaxy                 365
Sporting Kansas City      356
New York Red Bulls        356
Columbus Crew             354
New England Revolution    353
FC Dallas                 352
Colorado Rapids           351
DC United                 350
Chicago Fire              318
San Jose Earthquakes      314
Real Salt Lake            208
Houston Dynamo            193
Toronto FC                165
CD Chivas USA             164
Seattle Sounders          144
Philadelphia Union        119
Portland Timbers          107
Vancouver Whitecaps       104
Tampa Bay Mutiny           98
Montreal Impact            90
Miami Fusion               65
New York City FC           35
Orlando City               34
Name: visitor, dtype: int64

In [31]:
mls.vgoal.unique()

array([0, 1, 2, 3, 4, 5, 8, 6, 7])

## Date column



In [35]:
mls['Date'] = pd.to_datetime(mls['Date'])

mls = mls.set_index('Date').sort_index(ascending=True)

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [42]:
#mls.loc['2008':'2015']

In [44]:
mls.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4995 entries, 1996-04-06 to 2016-12-10
Data columns (total 5 columns):
Season     4995 non-null int64
home       4995 non-null object
hgoal      4995 non-null int64
visitor    4995 non-null object
vgoal      4995 non-null int64
dtypes: int64(3), object(2)
memory usage: 394.1+ KB


## Winner column
- create new colum with the winner value

In [45]:
mls['winner'] = np.where(mls['hgoal'] > mls['vgoal'], mls['home'], mls['visitor'])

In [47]:
mls.head()

Season                  home  hgoal                 visitor  \
Date                                                                      
1996-04-06    1996  San Jose Earthquakes      1               DC United   
1996-04-13    1996             LA Galaxy      2      New York Red Bulls   
1996-04-13    1996      Tampa Bay Mutiny      3  New England Revolution   
1996-04-13    1996         Columbus Crew      4               DC United   
1996-04-13    1996  Sporting Kansas City      3         Colorado Rapids   

            vgoal                winner  
Date                                     
1996-04-06      0  San Jose Earthquakes  
1996-04-13      1             LA Galaxy  
1996-04-13      2      Tampa Bay Mutiny  
1996-04-13      0         Columbus Crew  
1996-04-13      0  Sporting Kansas City

In [48]:
mls.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 4995 entries, 1996-04-06 to 2016-12-10
Data columns (total 6 columns):
Season     4995 non-null int64
home       4995 non-null object
hgoal      4995 non-null int64
visitor    4995 non-null object
vgoal      4995 non-null int64
winner     4995 non-null object
dtypes: int64(3), object(3)
memory usage: 433.2+ KB


## Save clean version to csv

In [49]:
mls.to_csv('clean_data/mls_clean.csv')

## Select from 2008: 2016

In [53]:
mls_08_16 = mls.loc['2008':'2016']

In [56]:
mls_08_16.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 2754 entries, 2008-03-29 to 2016-12-10
Data columns (total 6 columns):
Season     2754 non-null int64
home       2754 non-null object
hgoal      2754 non-null int64
visitor    2754 non-null object
vgoal      2754 non-null int64
winner     2754 non-null object
dtypes: int64(3), object(3)
memory usage: 150.6+ KB


## Save clean version to csv

In [60]:
mls_08_16.to_csv('clean_data/mls_08_16_clean.csv')

In [61]:
ls clean_data/

astros_08_17_clean.csv*       mls_clean.csv*         uh_08_17_clean.csv*
hou_rockets_08_17_clean.csv*  rice_08_17_clean.csv*
mls_08_16_clean.csv*          tsu_08_17_clean.csv*


In [62]:
## Finish

In [63]:
mls_08_16

Season                    home  hgoal                 visitor  \
Date                                                                        
2008-03-29    2008           Columbus Crew      2              Toronto FC   
2008-03-29    2008          Real Salt Lake      1            Chicago Fire   
2008-03-29    2008  New England Revolution      3          Houston Dynamo   
2008-03-29    2008    Sporting Kansas City      2               DC United   
2008-03-29    2008         Colorado Rapids      4               LA Galaxy   
2008-03-30    2008               FC Dallas      1           CD Chivas USA   
2008-04-03    2008            Chicago Fire      4  New England Revolution   
2008-04-04    2008               LA Galaxy      2    San Jose Earthquakes   
2008-04-05    2008    Sporting Kansas City      3         Colorado Rapids   
2008-04-05    2008      New York Red Bulls      2           Columbus Crew   
2008-04-05    2008               DC United      4              Toronto FC   
2008-04-06    2008           CD Chivas USA      3          Real Salt Lake   
2008-04-06    2008          Houston Dynamo      3               FC Dallas   
2008-04-09    2008    Sporting Kansas City      1  New England Revolution   
2008-04-12    2008    San Jose Earthquakes      0            Chicago Fire   
2008-04-12    2008           Columbus Crew      4           CD Chivas USA   
2008-04-12    2008  New England Revolution      0         Colorado Rapids   
2008-04-12    2008    Sporting Kansas City      0          Houston Dynamo   
2008-04-12    2008               FC Dallas      2      New York Red Bulls   
2008-04-12    2008          Real Salt Lake      4               DC United   
2008-04-13    2008               LA Galaxy      2              Toronto FC   
2008-04-17    2008               DC United      1           Columbus Crew   
2008-04-19    2008              Toronto FC      1          Real Salt Lake   
2008-04-19    2008      New York Red Bulls      1  New England Revolution   
2008-04-19    2008         Colorado Rapids      0    San Jose Earthquakes   
2008-04-20    2008               LA Galaxy      2          Houston Dynamo   
2008-04-20    2008            Chicago Fire      0    Sporting Kansas City   
2008-04-20    2008           CD Chivas USA      0               FC Dallas   
2008-04-24    2008               FC Dallas      0  New England Revolution   
2008-04-26    2008              Toronto FC      2    Sporting Kansas City   
...            ...                     ...    ...                     ...   
2016-10-16    2016        Portland Timbers      1         Colorado Rapids   
2016-10-16    2016          Houston Dynamo      0               LA Galaxy   
2016-10-16    2016               FC Dallas      2        Seattle Sounders   
2016-10-23    2016     Vancouver Whitecaps      4        Portland Timbers   
2016-10-23    2016              Toronto FC      3            Chicago Fire   
2016-10-23    2016    Sporting Kansas City      2    San Jose Earthquakes   
2016-10-23    2016        Seattle Sounders      2          Real Salt Lake   
2016-10-23    2016      Philadelphia Union      0      New York Red Bulls   
2016-10-23    2016            Orlando City      4               DC United   
2016-10-23    2016        New York City FC      4           Columbus Crew   
2016-10-23    2016  New England Revolution      3         Montreal Impact   
2016-10-23    2016               LA Galaxy      0               FC Dallas   
2016-10-23    2016         Colorado Rapids      1          Houston Dynamo   
2016-10-26    2016              Toronto FC      3      Philadelphia Union   
2016-10-26    2016               LA Galaxy      3          Real Salt Lake   
2016-10-27    2016               DC United      2         Montreal Impact   
2016-10-27    2016        Seattle Sounders      1    Sporting Kansas City   
2016-10-30    2016              Toronto FC      2        New York City FC   
2016-10-30    2016         Montreal Impact      1      New York Red Bulls   
2016-10-