In [1]:
import pandas as pd
import numpy as np
import glob, os
import re

## Location

In [2]:
ls sports_data/NCAA/

RU08_17.csv*  tsu08_11.csv*  tsu12_17.csv*  uh08_17.csv*


## Load Data

In [5]:
path = 'sports_data/NCAA/RU08_17.csv'
df = pd.read_csv(path)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 16 columns):
G              125 non-null int64
Date           125 non-null object
Time           63 non-null object
Day            125 non-null object
School         125 non-null object
Unnamed: 5     67 non-null object
Opponent       125 non-null object
Conf           125 non-null object
Unnamed: 8     125 non-null object
Pts            125 non-null int64
Opp            125 non-null int64
W              125 non-null int64
L              125 non-null int64
Streak         125 non-null object
Notes          26 non-null object
Unnamed: 15    1 non-null object
dtypes: int64(5), object(11)
memory usage: 15.7+ KB


In [135]:
df.head()

G         Date Time  Day School Unnamed: 5     Opponent      Conf  \
0  1  Aug 29 2008  NaN  Fri   Rice        NaN          SMU      CUSA   
1  2   Sep 6 2008  NaN  Sat   Rice          @      Memphis      CUSA   
2  3  Sep 13 2008  NaN  Sat   Rice          @   Vanderbilt       SEC   
3  4  Sep 20 2008  NaN  Sat   Rice          @    (7) Texas    Big 12   
4  5  Sep 27 2008  NaN  Sat   Rice        NaN  North Texas  Sun Belt   

  Unnamed: 8  Pts  Opp  W  L Streak Notes Unnamed: 15  
0          W   56   27  1  0    W 1   NaN         NaN  
1          W   42   35  2  0    W 2   NaN         NaN  
2          L   21   38  2  1    L 1   NaN         NaN  
3          L   10   52  2  2    L 2   NaN         NaN  
4          W   77   20  3  2    W 1   NaN         NaN

In [137]:
df['Notes'].unique()

array([nan, 'Texas Bowl (Texas Bowl (Houston TX))', 'Houston TX',
       'Armed Forces Bowl (Armed Forces Bowl (Fort Worth TX))',
       'Reliant Stadium - Houston TX', 'CUSA Championship Game',
       'Liberty Bowl (Memphis TN)', 'NBC', 'ESPN 2', 'FSN MSG+ ROOT-RM',
       'FCS', 'ASN CSN-BAY TCN-PHI', 'CBSSN', 'FSN MSG ROOT-PIT RM',
       'American Sports Network', 'FSN-OH DET MSG+ MASN2',
       'FSN MSG+ ROOT-PITT', 'FS1', 'ESPN', 'ESPN3'], dtype=object)

## Create slice with only needed columns

In [104]:
rice = df[['Date','Day','School','Pts','Unnamed: 5','Opponent','Opp','Unnamed: 8']]

In [105]:
rice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
Date          125 non-null object
Day           125 non-null object
School        125 non-null object
Pts           125 non-null int64
Unnamed: 5    67 non-null object
Opponent      125 non-null object
Opp           125 non-null int64
Unnamed: 8    125 non-null object
dtypes: int64(2), object(6)
memory usage: 7.9+ KB


In [106]:
rice.head()

Date  Day School  Pts Unnamed: 5     Opponent  Opp Unnamed: 8
0  Aug 29 2008  Fri   Rice   56        NaN          SMU   27          W
1   Sep 6 2008  Sat   Rice   42          @      Memphis   35          W
2  Sep 13 2008  Sat   Rice   21          @   Vanderbilt   38          L
3  Sep 20 2008  Sat   Rice   10          @    (7) Texas   52          L
4  Sep 27 2008  Sat   Rice   77        NaN  North Texas   20          W

## Inspect data

In [107]:
rice.Date.unique()  #ok

array(['Aug 29 2008', 'Sep 6 2008', 'Sep 13 2008', 'Sep 20 2008',
       'Sep 27 2008', 'Oct 4 2008', 'Oct 18 2008', 'Oct 25 2008',
       'Nov 1 2008', 'Nov 8 2008', 'Nov 22 2008', 'Nov 29 2008',
       'Dec 30 2008', 'Sep 5 2009', 'Sep 12 2009', 'Sep 19 2009',
       'Sep 26 2009', 'Oct 3 2009', 'Oct 10 2009', 'Oct 17 2009',
       'Oct 24 2009', 'Nov 7 2009', 'Nov 14 2009', 'Nov 21 2009',
       'Nov 28 2009', 'Sep 4 2010', 'Sep 11 2010', 'Sep 18 2010',
       'Sep 25 2010', 'Oct 2 2010', 'Oct 9 2010', 'Oct 16 2010',
       'Oct 23 2010', 'Nov 6 2010', 'Nov 13 2010', 'Nov 20 2010',
       'Nov 27 2010', 'Sep 3 2011', 'Sep 10 2011', 'Sep 24 2011',
       'Oct 1 2011', 'Oct 8 2011', 'Oct 15 2011', 'Oct 22 2011',
       'Oct 27 2011', 'Nov 5 2011', 'Nov 12 2011', 'Nov 19 2011',
       'Nov 26 2011', 'Aug 30 2012', 'Sep 8 2012', 'Sep 15 2012',
       'Sep 22 2012', 'Sep 29 2012', 'Oct 6 2012', 'Oct 13 2012',
       'Oct 20 2012', 'Oct 27 2012', 'Nov 3 2012', 'Nov 17 2012',
       'Nov 2

In [108]:
rice.Day.unique()  # ok

array(['Fri', 'Sat', 'Tue', 'Thu', 'Wed'], dtype=object)

In [109]:
rice.School.unique()  # OK

array(['Rice'], dtype=object)

In [110]:
rice.Pts.unique()  # OK

array([56, 42, 21, 10, 77, 28, 45, 49, 38, 35, 24, 17, 14, 13,  7, 30, 32,
       31, 34, 27, 62,  9, 20, 41,  6, 19, 25, 37, 51, 44, 36, 33, 23, 26,
       18, 16, 52, 65, 22,  3, 12])

In [111]:
rice['Unnamed: 5'].unique()  # need fix

array([nan, '@', 'N'], dtype=object)

In [112]:
rice.Opponent.unique()  # need fix

array(['SMU', 'Memphis', 'Vanderbilt', '(7) Texas', 'North Texas',
       'Tulsa', 'Southern Mississippi', 'Tulane', 'UTEP', 'Army',
       'Marshall', 'Houston', 'Western Michigan', 'UAB', 'Texas Tech',
       '(16) Oklahoma State', 'Navy', 'East Carolina', 'UCF',
       '(25) Houston', '(5) Texas', 'Northwestern', 'Baylor', 'Texas',
       'Purdue', '(17) Baylor', '(18) Houston', 'UCLA', 'Kansas',
       'Louisiana Tech', 'UTSA', 'Air Force', '(7) Texas A&M',
       'Florida Atlantic', 'New Mexico State', 'Mississippi State',
       '(17) Notre Dame', 'Old Dominion', 'Hawaii',
       'Florida International', '(21) Marshall', 'Fresno State', 'Wagner',
       '(5) Baylor', 'Western Kentucky', 'Charlotte', '(21) Baylor',
       'Prairie View A&M', 'Stanford', '(14) Stanford', 'Pitt'],
      dtype=object)

In [113]:
rice.Opp.unique()  # ok

array([27, 35, 38, 52, 20, 63, 40, 17, 44, 31, 10, 42, 14, 55, 41, 36, 49,
       29, 73, 34, 30, 64, 54, 23, 22, 56, 48,  6, 24, 37, 28,  7, 47, 21,
       19, 13, 45, 76, 16, 70, 26, 65, 46, 61, 62, 43])

In [114]:
rice['Unnamed: 8'].unique()  # ok

array(['W', 'L'], dtype=object)

## Cleanup columns
- Opponent: remove (#), and extra space

In [115]:
rice.Opponent.unique()

array(['SMU', 'Memphis', 'Vanderbilt', '(7) Texas', 'North Texas',
       'Tulsa', 'Southern Mississippi', 'Tulane', 'UTEP', 'Army',
       'Marshall', 'Houston', 'Western Michigan', 'UAB', 'Texas Tech',
       '(16) Oklahoma State', 'Navy', 'East Carolina', 'UCF',
       '(25) Houston', '(5) Texas', 'Northwestern', 'Baylor', 'Texas',
       'Purdue', '(17) Baylor', '(18) Houston', 'UCLA', 'Kansas',
       'Louisiana Tech', 'UTSA', 'Air Force', '(7) Texas A&M',
       'Florida Atlantic', 'New Mexico State', 'Mississippi State',
       '(17) Notre Dame', 'Old Dominion', 'Hawaii',
       'Florida International', '(21) Marshall', 'Fresno State', 'Wagner',
       '(5) Baylor', 'Western Kentucky', 'Charlotte', '(21) Baylor',
       'Prairie View A&M', 'Stanford', '(14) Stanford', 'Pitt'],
      dtype=object)

In [116]:
rice['Opponent'] = rice['Opponent'].str.replace(r"\(.*\)"," ")

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [117]:
rice.Opponent.unique()

array(['SMU', 'Memphis', 'Vanderbilt', '  Texas', 'North Texas', 'Tulsa',
       'Southern Mississippi', 'Tulane', 'UTEP', 'Army', 'Marshall',
       'Houston', 'Western Michigan', 'UAB', 'Texas Tech',
       '  Oklahoma State', 'Navy', 'East Carolina', 'UCF', '  Houston',
       'Northwestern', 'Baylor', 'Texas', 'Purdue', '  Baylor', 'UCLA',
       'Kansas', 'Louisiana Tech', 'UTSA', 'Air Force', '  Texas A&M',
       'Florida Atlantic', 'New Mexico State', 'Mississippi State',
       '  Notre Dame', 'Old Dominion', 'Hawaii', 'Florida International',
       '  Marshall', 'Fresno State', 'Wagner', 'Western Kentucky',
       'Charlotte', 'Prairie View A&M', 'Stanford', '  Stanford', 'Pitt'],
      dtype=object)

In [119]:
rice['Opponent'] = rice['Opponent'].str.strip()

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [120]:
rice.Opponent.unique()

array(['SMU', 'Memphis', 'Vanderbilt', 'Texas', 'North Texas', 'Tulsa',
       'Southern Mississippi', 'Tulane', 'UTEP', 'Army', 'Marshall',
       'Houston', 'Western Michigan', 'UAB', 'Texas Tech',
       'Oklahoma State', 'Navy', 'East Carolina', 'UCF', 'Northwestern',
       'Baylor', 'Purdue', 'UCLA', 'Kansas', 'Louisiana Tech', 'UTSA',
       'Air Force', 'Texas A&M', 'Florida Atlantic', 'New Mexico State',
       'Mississippi State', 'Notre Dame', 'Old Dominion', 'Hawaii',
       'Florida International', 'Fresno State', 'Wagner',
       'Western Kentucky', 'Charlotte', 'Prairie View A&M', 'Stanford',
       'Pitt'], dtype=object)

## fix 

In [121]:
rice['Unnamed: 5'].unique()  # need fix

array([nan, '@', 'N'], dtype=object)

In [122]:
rice['Unnamed: 5'].value_counts(dropna=False)

@      61
NaN    58
N       6
Name: Unnamed: 5, dtype: int64

## Change values of '@` to 'Away
- create boolean mask to find rows whose value is '@

In [129]:
rice['Unnamed: 5'] = rice['Unnamed: 5'].replace('@','away')

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [132]:
rice['Unnamed: 5'] = rice['Unnamed: 5'].fillna('home')

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [133]:
rice['Unnamed: 5'].value_counts(dropna=False)

away    61
home    58
N        6
Name: Unnamed: 5, dtype: int64

#### Show values of 'N'

- create boolean mask to find rows whose value is 'N

In [134]:
n_val = rice['Unnamed: 5']  =='N'
rice[n_val]

Date  Day School  Pts Unnamed: 5           Opponent  Opp  \
53   Sep 29 2012  Sat   Rice   14          N            Houston   35   
61   Dec 29 2012  Sat   Rice   33          N          Air Force   14   
64   Sep 21 2013  Sat   Rice   26          N            Houston   31   
75   Dec 31 2013  Tue   Rice    7          N  Mississippi State   44   
88   Dec 24 2014  Wed   Rice   30          N       Fresno State    6   
113  Aug 26 2017  Sat   Rice    7          N           Stanford   62   

    Unnamed: 8  
53           L  
61           W  
64           L  
75           L  
88           W  
113          L

## google search
- rice v houston : away
- rice v air force : away
- rice v houston : away (reliant stadium)
- rice v Mississippi State : away (MEMPHIS)
- rice v Frenso State : away (HAWAI'I BOWL)
- rice v Stanford : away (sydney)

In [138]:
rice['Unnamed: 5'] = rice['Unnamed: 5'].replace('N','away')

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [139]:
rice['Unnamed: 5'].value_counts(dropna=False)

away    67
home    58
Name: Unnamed: 5, dtype: int64

In [140]:
rice.head()

Date  Day School  Pts Unnamed: 5     Opponent  Opp Unnamed: 8
0  Aug 29 2008  Fri   Rice   56       home          SMU   27          W
1   Sep 6 2008  Sat   Rice   42       away      Memphis   35          W
2  Sep 13 2008  Sat   Rice   21       away   Vanderbilt   38          L
3  Sep 20 2008  Sat   Rice   10       away        Texas   52          L
4  Sep 27 2008  Sat   Rice   77       home  North Texas   20          W

In [141]:
rice.rename(columns={'Unnamed: 8':'win_lost',
                  'Unnamed: 5':'home_away'}, inplace=True)

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/pandas/core/frame.py:3027: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  return super(DataFrame, self).rename(**kwargs)


In [142]:
rice.head()

Date  Day School  Pts home_away     Opponent  Opp win_lost
0  Aug 29 2008  Fri   Rice   56      home          SMU   27        W
1   Sep 6 2008  Sat   Rice   42      away      Memphis   35        W
2  Sep 13 2008  Sat   Rice   21      away   Vanderbilt   38        L
3  Sep 20 2008  Sat   Rice   10      away        Texas   52        L
4  Sep 27 2008  Sat   Rice   77      home  North Texas   20        W

## Convert Date to datetime

In [145]:
rice['Date'] = pd.to_datetime(rice['Date'])

/home/salas/miniconda3/envs/springboard/lib/python3.6/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [146]:
rice.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 8 columns):
Date         125 non-null datetime64[ns]
Day          125 non-null object
School       125 non-null object
Pts          125 non-null int64
home_away    125 non-null object
Opponent     125 non-null object
Opp          125 non-null int64
win_lost     125 non-null object
dtypes: datetime64[ns](1), int64(2), object(5)
memory usage: 7.9+ KB


## Reindex dataframe by date

- reindex the dataframe and sort the dates

In [147]:
rice = rice.set_index('Date').sort_index(ascending=True)

In [148]:
rice.info()

<class 'pandas.core.frame.DataFrame'>
DatetimeIndex: 125 entries, 2008-08-29 to 2017-11-25
Data columns (total 7 columns):
Day          125 non-null object
School       125 non-null object
Pts          125 non-null int64
home_away    125 non-null object
Opponent     125 non-null object
Opp          125 non-null int64
win_lost     125 non-null object
dtypes: int64(2), object(5)
memory usage: 7.8+ KB


In [150]:
rice.head()

Day School  Pts home_away     Opponent  Opp win_lost
Date                                                            
2008-08-29  Fri   Rice   56      home          SMU   27        W
2008-09-06  Sat   Rice   42      away      Memphis   35        W
2008-09-13  Sat   Rice   21      away   Vanderbilt   38        L
2008-09-20  Sat   Rice   10      away        Texas   52        L
2008-09-27  Sat   Rice   77      home  North Texas   20        W

## Save clean data to  to csv

In [151]:
rice.to_csv('clean_data/rice_08_17_clean.csv')

In [152]:
ls clean_data/

astros_08_17_clean.csv*  rice_08_17_clean.csv*  uh_08_17_clean.csv*


In [153]:
## finish